CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS users (
    id          SERIAL PRIMARY KEY,
    email       VARCHAR(255) UNIQUE NOT NULL,
    username    VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    avatar_url  TEXT,
    bio         TEXT,
    daily_notification BOOLEAN DEFAULT FALSE,
    notif_email VARCHAR(255),
    created_at  TIMESTAMP DEFAULT NOW(),
    updated_at  TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS genres (
    id    SERIAL PRIMARY KEY,
    name  VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS books (
    id          SERIAL PRIMARY KEY,
    title       VARCHAR(500) NOT NULL,
    author      VARCHAR(255) NOT NULL,
    year        INTEGER,
    description TEXT,
    cover_url   TEXT,
    isbn        VARCHAR(20),
    added_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at  TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS book_genres (
    book_id  INTEGER REFERENCES books(id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genres(id) ON DELETE CASCADE,
    PRIMARY KEY (book_id, genre_id)
);

CREATE TABLE IF NOT EXISTS user_books (
    id          SERIAL PRIMARY KEY,
    user_id     INTEGER REFERENCES users(id) ON DELETE CASCADE,
    book_id     INTEGER REFERENCES books(id) ON DELETE CASCADE,
    status      VARCHAR(20) CHECK (status IN ('completed', 'reading', 'to_read')) NOT NULL,
    rating      SMALLINT CHECK (rating BETWEEN 1 AND 5),
    review      TEXT,
    progress    SMALLINT DEFAULT 0 CHECK (progress BETWEEN 0 AND 100),
    start_date  DATE,
    finish_date DATE,
    created_at  TIMESTAMP DEFAULT NOW(),
    updated_at  TIMESTAMP DEFAULT NOW(),
    UNIQUE(user_id, book_id)
);

CREATE TABLE IF NOT EXISTS nestie_conversations (
    id         SERIAL PRIMARY KEY,
    user_id    INTEGER REFERENCES users(id) ON DELETE CASCADE,
    role       VARCHAR(20) CHECK (role IN ('user', 'assistant')),
    content    TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_books_user ON user_books(user_id);
CREATE INDEX IF NOT EXISTS idx_user_books_status ON user_books(user_id, status);
CREATE INDEX IF NOT EXISTS idx_books_author ON books(author);
CREATE INDEX IF NOT EXISTS idx_nestie_user ON nestie_conversations(user_id, created_at);


INSERT INTO genres (name) VALUES
    ('Adventure'),
    ('Allegory'),
    ('American Literature'),
    ('Biography'),
    ('Business'),
    ('Christmas'),
    ('Classic'),
    ('Coming-of-age'),
    ('Contemporary'),
    ('Crime'),
    ('Detective'),
    ('Drama'),
    ('Dystopian'),
    ('Essay'),
    ('Fairy Tale'),
    ('Fantasy'),
    ('Fiction'),
    ('Gothic'),
    ('Historical'),
    ('History'),
    ('Horror'),
    ('Inspirational'),
    ('Legal'),
    ('Letters'),
    ('Literary Fiction'),
    ('Medical'),
    ('Memoir'),
    ('Mystery'),
    ('Mythology'),
    ('Non-fiction'),
    ('Novella'),
    ('Personal Development'),
    ('Philosophical'),
    ('Philosophy'),
    ('Play'),
    ('Poetry'),
    ('Political Fiction'),
    ('Psychological'),
    ('Psychology'),
    ('Relationships'),
    ('Romance'),
    ('Romanian Literature'),
    ('Satire'),
    ('Science'),
    ('Science Fiction'),
    ('Self-help'),
    ('Thriller'),
    ('War'),
    ('Young Adult')
ON CONFLICT (name) DO NOTHING;

INSERT INTO books (title, author, year, description, cover_url) VALUES
    ('nan', 'George Orwell', 1949, 'A dystopian novel about a totalitarian regime that controls truth and thought.', 'nan'),
    ('Fahrenheit 451', 'Ray Bradbury', 1953, 'A future society where books are banned and burned to suppress ideas.', 'nan'),
    ('Rebecca', 'Daphne du Maurier', 1938, 'A young woman becomes entangled in the dark secrets of a grand estate.', 'nan'),
    ('Adam si Eva', 'Liviu Rebreanu', 1925, 'A philosophical love story exploring destiny and reincarnation.', 'nan'),
    ('Moartea lebedei', 'Ion Grecea', 1900, 'A poetic exploration of life, love, and human emotions.', 'nan'),
    ('Every Note Played', 'Lisa Genova', 2018, 'A story about a pianist losing control over his body due to illness.', 'nan'),
    ('The Tattooist of Auschwitz', 'Heather Morris', 2018, 'A story of love and survival set during the Holocaust.', 'nan'),
    ('The Long Road of Auma', 'Eucabeth A. Odhiambo', 2006, 'A young girl’s journey through hardship and resilience in Africa.', 'nan'),
    ('The Haunting of Hill House', 'Shirley Jackson', 1959, 'A chilling tale of a haunted house and psychological fear.', 'nan'),
    ('Nerantula', 'Panait Istrati', 1927, 'A story exploring human instincts and survival.', 'nan'),
    ('Seven Days', 'Eve Ainsworth', 2014, 'A teenager struggles with grief and difficult life choices.', 'nan'),
    ('Elizabeth Is Missing', 'Emma Healey', 2014, 'A mystery about an elderly woman losing her memory.', 'nan'),
    ('Pygmalion', 'George Bernard Shaw', 1913, 'A play about transformation, identity, and love.', 'nan'),
    ('The Hound of the Baskervilles', 'Arthur Conan Doyle', 1902, 'A detective investigates a mysterious and supernatural case.', 'nan'),
    ('Imperativele adolescentei', 'Chris Simion', 2016, 'A reflection on youth, identity, and personal growth.', 'nan'),
    ('The Last Time We Say Goodbye', 'Cynthia Hand', 2015, 'A story about grief and coping with loss.', 'nan'),
    ('Ion', 'Liviu Rebreanu', 1920, 'A classic novel about rural life and social struggles.', 'nan'),
    ('The Ballad of Songbirds and Snakes', 'Suzanne Collins', 2020, 'A dystopian story of survival and rebellion against oppression.', 'nan'),
    ('Murder at the Vicarage', 'Agatha Christie', 1930, 'A murder mystery set in a quiet English village.', 'nan'),
    ('Invitatie la vals', 'Mihail Drumes', 1935, 'A romantic story about love and societal expectations.', 'nan'),
    ('Piranesi', 'Susanna Clarke', 2020, 'A mysterious and surreal exploration of reality and identity.', 'nan'),
    ('Misery', 'Stephen King', 1987, 'A psychological horror story about obsession and madness.', 'nan'),
    ('Circe', 'Madeline Miller', 2018, 'A retelling of Greek mythology through the eyes of Circe.', 'nan'),
    ('The Great Gatsby', 'F. Scott Fitzgerald', 1925, 'A critique of wealth, love, and the American Dream.', 'nan'),
    ('Mockingjay', 'Suzanne Collins', 2010, 'A continuation of a dystopian rebellion against authority.', 'nan'),
    ('All Quiet on the Western Front', 'Erich Maria Remarque', 1929, 'A powerful anti-war novel depicting the horrors of World War I.', 'nan'),
    ('Emma', 'Jane Austen', 1815, 'A romantic novel about relationships and personal growth.', 'nan'),
    ('American Dirt', 'Jeanine Cummins', 2020, 'A story about immigration, family, and survival.', 'nan'),
    ('Dear Edward', 'Ann Napolitano', 2020, 'A boy’s journey through grief and self-discovery.', 'nan'),
    ('The Silent Patient', 'Alex Michaelides', 2019, 'A psychological thriller involving secrets and trauma.', 'nan'),
    ('Macbeth', 'William Shakespeare', 1606, 'A tragic play about ambition and downfall.', 'nan'),
    ('Daring Greatly', 'Brené Brown', 2012, 'A guide to embracing vulnerability and courage.', 'nan'),
    ('Romeo and Juliet', 'William Shakespeare', 1597, 'A timeless love story of two young lovers.', 'nan'),
    ('Atomic Habits', 'James Clear', 2018, 'A practical guide to building good habits.', 'nan'),
    ('The Little Prince', 'Antoine de Saint-Exupéry', 1943, 'A philosophical tale about innocence and human nature.', 'nan'),
    ('First They Killed My Father', 'Loung Ung', 2000, 'A memoir about surviving genocide and loss.', 'nan'),
    ('Frankenstein', 'Mary Shelley', 1818, 'A gothic novel about science and creation.', 'nan'),
    ('The Romanovs', 'Candace Fleming', 2016, 'A historical account of a powerful royal family.', 'nan'),
    ('Steppenwolf', 'Hermann Hesse', 1927, 'A philosophical novel about identity and existence.', 'nan'),
    ('The Count of Monte Cristo', 'Alexandre Dumas', 1844, 'An adventure story of revenge and justice.', 'nan'),
    ('The Boy in the Striped Pyjamas', 'John Boyne', 2006, 'A story about innocence during wartime.', 'nan'),
    ('The Book Thief', 'Markus Zusak', 2005, 'A narrative about survival and moral choices in war.', 'nan'),
    ('The Bell Jar', 'Sylvia Plath', 1963, 'A coming-of-age novel about identity and mental health.', 'nan'),
    ('Breakfast at Tiffany''s', 'Truman Capote', 1958, 'A story of loneliness and self-reflection.', 'nan'),
    ('Murder on the Orient Express', 'Agatha Christie', 1958, 'A classic portrayal of urban life and relationships.', 'nan'),
    ('The Catcher in the Rye', 'J.D. Salinger', 1934, 'A detective investigates a murder on a train.', 'nan'),
    ('And Then There Were None', 'Agatha Christie', 1951, 'A coming-of-age story about teenage rebellion.', 'nan'),
    ('The Dinosaur Feather', 'Sissel-Jo Gazan', 1939, 'A mystery involving multiple suspects and hidden truths.', 'nan'),
    ('Baltagul', 'Mihail Sadoveanu', 2013, 'A literary novel exploring human relationships.', 'nan'),
    ('Moara cu noroc', 'Ioan Slavici', 1930, 'A Romanian classic about tradition and justice.', 'nan'),
    ('Man''s Search for Meaning', 'Viktor E. Frankl', 1881, 'A story about greed and moral consequences.', 'nan'),
    ('25 Ways to Win People Over', 'John C. Maxwell', 1946, 'A philosophical exploration of life’s meaning.', 'nan'),
    ('Fresh Water for Flowers', 'Valérie Perrin', 1936, 'A self-help book about influencing people and success.', 'nan'),
    ('Letters to a Young Poet', 'Rainer Maria Rilke', 2016, 'A romantic story about love and healing.', 'nan'),
    ('Behind Her Eyes', 'Sarah Pinborough', 2018, 'A collection of letters about art, life, and philosophy.', 'nan'),
    ('The Postman Always Rings Twice', 'James M. Cain', 1937, 'A psychological thriller involving manipulation and deception.', 'nan'),
    ('Notre-Dame de Paris', 'Victor Hugo', 2017, 'A crime story driven by obsession and fate.', 'nan'),
    ('Nunta in cer', 'Mircea Eliade', 2017, 'A historical novel set in Paris.', 'nan'),
    ('Povestea lui Harap-Alb', 'Ion Creanga', 1931, 'A philosophical love story set in a spiritual context.', 'nan'),
    ('Maitreyi', 'Mircea Eliade', 1936, 'A Romanian fairy tale about courage and adventure.', 'nan'),
    ('The Hunger Games', 'Suzanne Collins', 1877, 'A story about love and self-discovery.', 'nan'),
    ('Catching Fire', 'Suzanne Collins', 1933, 'A dystopian survival story in a controlled society.', 'nan'),
    ('The Most Cruel Women in History', 'Alain Leclercq', 1922, 'A continuation of a rebellion against oppression.', 'nan'),
    ('House of Gucci', 'Sara Gay Forden', 2008, 'A historical overview of influential women.', 'nan'),
    ('Razbunarea slutilor', 'Rodica Ojog-Brasoveanu', 2015, 'A biography of a famous fashion dynasty.', 'nan'),
    ('Poezii', 'George Cosbuc', 2015, 'A mystery involving deception and revenge.', 'nan'),
    ('Alice''s Adventures in Wonderland', 'Lewis Carroll', 1994, 'A collection of poetic works exploring nature and emotions.', 'nan'),
    ('Through the Looking-Glass', 'Lewis Carroll', 1865, 'A fantasy adventure in a magical world.', 'nan'),
    ('Oscar and the Lady in Pink', 'Éric Emmanuel Schmitt', 1871, 'A sequel exploring a mirror world.', 'nan'),
    ('The Promise of a Lie', 'Howard Roughan', 2001, 'A philosophical story about illness and compassion.', 'nan'),
    ('The Midnight Library', 'Matt Haig', 2010, 'A thriller involving secrets and lies.', 'nan'),
    ('Barbatii sunt niste porci', 'Rodica Ojog-Brasoveanu', 2020, 'A philosophical exploration of life choices.', 'nan'),
    ('The Prophet', 'Kahlil Gibran', 1997, 'A satirical look at human behavior.', 'nan'),
    ('Lord of the Flies', 'William Golding', 1923, 'An allegorical novel about power and corruption.', 'nan'),
    ('The Diary of a Young Girl', 'Anne Frank', 1954, 'A personal diary of a young girl during war.', 'nan'),
    ('Too Loud a Solitude', 'Bohumil Hrabal', 1947, 'A literary reflection on solitude and existence.', 'nan'),
    ('Setea muntelui de sare', 'Marin Sorescu', 1976, 'A poetic drama exploring human emotions.', 'nan'),
    ('12 Creators Who Changed History', 'Bertrand Meyer-Stabley', 1965, 'A historical account of influential figures.', 'nan'),
    ('How to Win Friends and Influence People', 'Dale Carnegie', 1934, 'A self-help guide for personal success.', 'nan'),
    ('Sharp Objects', 'Gillian Flynn', 1956, 'A psychological thriller about dark secrets.', 'nan'),
    ('Anna Karenina', 'Leo Tolstoy', 2018, 'A classic romantic novel about society and love.', 'nan'),
    ('The Screwtape Letters', 'C.S. Lewis', 2012, 'A satirical critique of society.', 'nan'),
    ('A Gentleman in Moscow', 'Amor Towles', 2020, 'A philosophical work on morality and religion.', 'nan'),
    ('Animal Farm', 'George Orwell', 1877, 'A dystopian allegory about political systems.', 'nan'),
    ('The Flowers of Evil', 'Charles Baudelaire', 1945, 'A collection of symbolic poems.', 'nan'),
    ('Jar City', 'Arnaldur Indridason', 1857, 'A crime story with suspenseful twists.', 'nan'),
    ('Mesterul Manole', 'Lucian Blaga', 2000, 'A mythological drama rooted in folklore.', 'nan'),
    ('Notes from Underground', 'Fyodor Dostoevsky', 1927, 'A philosophical narrative on human existence.', 'nan'),
    ('Uncle Tom’s Cabin', 'Harriet Beecher Stowe', 1864, 'A classic novel about racism and justice.', 'nan'),
    ('Poezii', 'Mihai Eminescu', 1908, 'A collection of poetic works reflecting Romanian identity and philosophy.', 'nan'),
    ('One Flew Over the Cuckoo’s Nest', 'Ken Kesey', 1852, 'A psychological novel about mental struggles.', 'nan'),
    ('The Unwomanly Face of War', 'Svetlana Alexievich', 2002, 'A historical account of war experiences.', 'nan'),
    ('Great Stories of an Antiquary', 'M.R. James', 2015, 'A gothic horror story about transformation.', 'nan'),
    ('Ultima noapte de dragoste, intaia noapte de razboi', 'Camil Petrescu', 1890, 'A philosophical essay about time.', 'nan'),
    ('On the Shortness of Life', 'Seneca', 2003, 'A detective story involving murder and intrigue.', 'nan'),
    ('Cianura pentru un suras', 'Rodica Ojog-Brasoveanu', 2020, 'A philosophical exploration of self-awareness.', 'nan'),
    ('Crime and Punishment', 'Fyodor Dostoevsky', 2020, 'A detective investigates a mysterious crime.', 'nan'),
    ('The Power of Now', 'Eckhart Tolle', 2020, 'A contemporary story about relationships and nature.', 'nan'),
    ('A Study in Scarlet', 'Arthur Conan Doyle', 1847, 'A detective story with multiple twists.', 'nan'),
    ('Where the Crawdads Sing', 'Delia Owens', 2020, 'A Romanian novel about rural life.', 'nan'),
    ('The Sign of Four', 'Arthur Conan Doyle', 2020, 'A collection of romantic poetry.', 'nan'),
    ('Morometii', 'Marin Preda', 1866, 'A memoir about illness and mortality.', 'nan'),
    ('111 cele mai frumoase poezii de dragoste din literatura romana', 'Marius Chivu', 2020, 'A gothic novel about beauty and corruption.', 'nan'),
    ('When Breath Becomes Air', 'Paul Kalanithi', 2016, 'A satirical work about societal clichés.', 'nan'),
    ('The Picture of Dorian Gray', 'Oscar Wilde', 1890, 'A philosophical reflection on love.', 'nan'),
    ('Dictionary of Received Ideas', 'Gustave Flaubert', 2017, 'A psychological story about chess and obsession.', 'nan'),
    ('The Little Book of Love', 'Kahlil Gibran', 1890, 'A Romanian classic about society and class.', 'nan'),
    ('The Queen''s Gambit', 'Walter Tevis', 1890, 'A dystopian novel about a controlled society.', 'nan'),
    ('Enigma Otiliei', 'George Calinescu', 1960, 'A self-help book about relationships.', 'nan'),
    ('The Handmaid’s Tale', 'Margaret Atwood', 1926, 'A philosophical reflection on death and meaning.', 'nan'),
    ('The 5 Love Languages', 'Gary Chapman', 1915, 'A thriller involving conspiracies and secrets.', 'nan'),
    ('Staring at the Sun', 'Irvin Yalom', 1985, 'A fantasy story about a young wizard discovering his powers.', 'nan'),
    ('The Da Vinci Code', 'Dan Brown', 1985, 'A continuation of magical adventures and friendships.', 'nan'),
    ('Harry Potter and the Philosopher’s Stone', 'J.K Rowling', 2000, 'A darker journey in a magical world facing danger.', 'nan'),
    ('Harry Potter and the Chamber of Secrets', 'J.K Rowling', 2000, 'A tournament filled with magical challenges and risks.', 'nan'),
    ('Harry Potter and the Prisoner of Azkaban', 'J.K Rowling', 1997, 'A fight against a rising dark force threatening the world.', 'nan'),
    ('Harry Potter and The Goblet of Fire', 'J.K Rowling', 1998, 'A simple story about life, perseverance, and the sea.', 'nan'),
    ('Harry Potter and the Order of the Phoenix', 'J.K Rowling', 1999, 'A story about mathematics and human connection.', 'nan'),
    ('The Old Man and the Sea', 'Ernest Hemingway', 2000, 'A continuation of magical conflict and destiny.', 'nan'),
    ('The Housekeeper and the Professor', 'Yoko Ogawa', 2003, 'A final battle between good and evil.', 'nan'),
    ('Harry Potter and the Half-Blood Prince', 'J.K Rowling', 2005, 'A classic Christmas tale of redemption and transformation.', 'nan'),
    ('Harry Potter and the Deathly Hallows', 'J.K Rowling', 1927, 'A legal drama exploring justice and truth.', 'nan'),
    ('A Christmas Carol', 'Charles Dickens', 2003, 'A philosophical story about relationships and morality.', 'nan'),
    ('Apararea are cuvantul', 'Petre Bellu', 2005, 'A story about death and self-realization.', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1404669200i/12166726.jpg'),
    ('Drive Your Plow Over the Bones of the Dead', 'Olga Tokarczuk', 2009, 'A mysterious investigation into a series of unusual deaths in a remote village.', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1565725457l/51648276.jpg'),
    ('The Kreutzer Sonata', 'Leo Tolstoy', 2007, 'A novel about racial injustice and moral growth.', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1657554522i/141077.jpg'),
    ('The Death of Ivan Ilych', 'Leo Tolstoy', 2007, 'A detective story about a mysterious and complex murder.', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1663546974i/18386.jpg'),
    ('To Kill a Mockingbird', 'Harper Lee', 1843, 'A philosophical tale about transformation and identity.', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1612238791i/56916837.jpg'),
    ('The Murder of Roger Ackroyd', 'Agatha Christie', 2020, 'A story about obsession, scent, and crime.', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1389734015i/16328.jpg'),
    ('The Metamorphosis', 'Franz Kafka', 1889, 'A philosophical guide to living a meaningful life.', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1646444605i/485894.jpg'),
    ('Perfume: The Story of a Murderer', 'Patrick Süskind', 1886, 'A novel about love, memory, and nostalgia.', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1409112276i/343.jpg'),
    ('The Art of Living', 'Epictetus', 1960, 'A tragic love story driven by intense emotions.', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1388969321i/24618.jpg'),
    ('Norwegian Wood', 'Haruki Murakami', 1926, 'A horror story about telekinesis and revenge.', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1713542603i/11297.jpg'),
    ('The Sorrows of Young Werther', 'Johann Wolfgang von Goethe', 1915, 'A crime story involving investigation and mystery.', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1758424070i/16640.jpg'),
    ('Carrie', 'Stephen King', 1915, 'A contemporary story about science, life, and resilience.', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1771367607i/10592.jpg'),
    ('Crima prin mica publicitate', 'Rodica Ojog-Brasoveanu', 2005, 'A mystery involving murder under the sun.', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1330683794i/13507716.jpg'),
    ('Lessons in Chemistry', 'Bonnie Garmus', 1867, 'A self-help book about mental health and survival.', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1759925297i/242528917.jpg'),
    ('Evil Under the Sun', 'Agatha Christie', 2000, 'A psychological thriller involving family secrets and tension.', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1386922974i/16305.jpg'),
    ('Reasons to Stay Alive', 'Matt Haig', 2000, 'A collection of poetic works exploring Romanian culture and identity.', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1453057036i/25733573.jpg'),
    ('The Perfect Son', 'Freida McFadden', 1974, 'A collection of poetic works reflecting love, philosophy, and nature.', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1570489697l/52616342.jpg')
ON CONFLICT DO NOTHING;

INSERT INTO book_genres (book_id, genre_id) VALUES
    ((SELECT id FROM books WHERE title='nan' LIMIT 1), (SELECT id FROM genres WHERE name='Dystopian' LIMIT 1)),
    ((SELECT id FROM books WHERE title='nan' LIMIT 1), (SELECT id FROM genres WHERE name='Political Fiction' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Fahrenheit 451' LIMIT 1), (SELECT id FROM genres WHERE name='Dystopian' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Fahrenheit 451' LIMIT 1), (SELECT id FROM genres WHERE name='Science Fiction' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Rebecca' LIMIT 1), (SELECT id FROM genres WHERE name='Gothic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Rebecca' LIMIT 1), (SELECT id FROM genres WHERE name='Romance' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Adam si Eva' LIMIT 1), (SELECT id FROM genres WHERE name='Philosophical' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Adam si Eva' LIMIT 1), (SELECT id FROM genres WHERE name='Romance' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Moartea lebedei' LIMIT 1), (SELECT id FROM genres WHERE name='Poetry' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Moartea lebedei' LIMIT 1), (SELECT id FROM genres WHERE name='Drama' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Every Note Played' LIMIT 1), (SELECT id FROM genres WHERE name='Contemporary' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Every Note Played' LIMIT 1), (SELECT id FROM genres WHERE name='Drama' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Tattooist of Auschwitz' LIMIT 1), (SELECT id FROM genres WHERE name='Historical' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Tattooist of Auschwitz' LIMIT 1), (SELECT id FROM genres WHERE name='Romance' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Long Road of Auma' LIMIT 1), (SELECT id FROM genres WHERE name='Biography' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Long Road of Auma' LIMIT 1), (SELECT id FROM genres WHERE name='Inspirational' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Haunting of Hill House' LIMIT 1), (SELECT id FROM genres WHERE name='Horror' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Haunting of Hill House' LIMIT 1), (SELECT id FROM genres WHERE name='Gothic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Nerantula' LIMIT 1), (SELECT id FROM genres WHERE name='Literary Fiction' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Seven Days' LIMIT 1), (SELECT id FROM genres WHERE name='Young Adult' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Seven Days' LIMIT 1), (SELECT id FROM genres WHERE name='Contemporary' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Elizabeth Is Missing' LIMIT 1), (SELECT id FROM genres WHERE name='Mystery' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Elizabeth Is Missing' LIMIT 1), (SELECT id FROM genres WHERE name='Thriller' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Pygmalion' LIMIT 1), (SELECT id FROM genres WHERE name='Drama' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Pygmalion' LIMIT 1), (SELECT id FROM genres WHERE name='Play' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Hound of the Baskervilles' LIMIT 1), (SELECT id FROM genres WHERE name='Detective' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Hound of the Baskervilles' LIMIT 1), (SELECT id FROM genres WHERE name='Mystery' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Imperativele adolescentei' LIMIT 1), (SELECT id FROM genres WHERE name='Contemporary' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Imperativele adolescentei' LIMIT 1), (SELECT id FROM genres WHERE name='Drama' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Last Time We Say Goodbye' LIMIT 1), (SELECT id FROM genres WHERE name='Young Adult' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Last Time We Say Goodbye' LIMIT 1), (SELECT id FROM genres WHERE name='Contemporary' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Ion' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Ion' LIMIT 1), (SELECT id FROM genres WHERE name='Literary Fiction' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Ballad of Songbirds and Snakes' LIMIT 1), (SELECT id FROM genres WHERE name='Dystopian' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Ballad of Songbirds and Snakes' LIMIT 1), (SELECT id FROM genres WHERE name='Young Adult' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Murder at the Vicarage' LIMIT 1), (SELECT id FROM genres WHERE name='Mystery' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Murder at the Vicarage' LIMIT 1), (SELECT id FROM genres WHERE name='Crime' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Invitatie la vals' LIMIT 1), (SELECT id FROM genres WHERE name='Romance' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Invitatie la vals' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Piranesi' LIMIT 1), (SELECT id FROM genres WHERE name='Fantasy' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Piranesi' LIMIT 1), (SELECT id FROM genres WHERE name='Literary Fiction' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Misery' LIMIT 1), (SELECT id FROM genres WHERE name='Horror' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Misery' LIMIT 1), (SELECT id FROM genres WHERE name='Thriller' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Circe' LIMIT 1), (SELECT id FROM genres WHERE name='Mythology' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Circe' LIMIT 1), (SELECT id FROM genres WHERE name='Fantasy' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Great Gatsby' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Great Gatsby' LIMIT 1), (SELECT id FROM genres WHERE name='Literary Fiction' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Mockingjay' LIMIT 1), (SELECT id FROM genres WHERE name='Dystopian' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Mockingjay' LIMIT 1), (SELECT id FROM genres WHERE name='Young Adult' LIMIT 1)),
    ((SELECT id FROM books WHERE title='All Quiet on the Western Front' LIMIT 1), (SELECT id FROM genres WHERE name='War' LIMIT 1)),
    ((SELECT id FROM books WHERE title='All Quiet on the Western Front' LIMIT 1), (SELECT id FROM genres WHERE name='Historical' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Emma' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Emma' LIMIT 1), (SELECT id FROM genres WHERE name='Romance' LIMIT 1)),
    ((SELECT id FROM books WHERE title='American Dirt' LIMIT 1), (SELECT id FROM genres WHERE name='Contemporary' LIMIT 1)),
    ((SELECT id FROM books WHERE title='American Dirt' LIMIT 1), (SELECT id FROM genres WHERE name='Drama' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Dear Edward' LIMIT 1), (SELECT id FROM genres WHERE name='Contemporary' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Dear Edward' LIMIT 1), (SELECT id FROM genres WHERE name='Drama' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Silent Patient' LIMIT 1), (SELECT id FROM genres WHERE name='Psychological' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Silent Patient' LIMIT 1), (SELECT id FROM genres WHERE name='Thriller' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Macbeth' LIMIT 1), (SELECT id FROM genres WHERE name='Drama' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Macbeth' LIMIT 1), (SELECT id FROM genres WHERE name='Play' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Daring Greatly' LIMIT 1), (SELECT id FROM genres WHERE name='Self-help' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Daring Greatly' LIMIT 1), (SELECT id FROM genres WHERE name='Psychology' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Romeo and Juliet' LIMIT 1), (SELECT id FROM genres WHERE name='Drama' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Romeo and Juliet' LIMIT 1), (SELECT id FROM genres WHERE name='Romance' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Atomic Habits' LIMIT 1), (SELECT id FROM genres WHERE name='Self-help' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Atomic Habits' LIMIT 1), (SELECT id FROM genres WHERE name='Personal Development' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Little Prince' LIMIT 1), (SELECT id FROM genres WHERE name='Philosophical' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Little Prince' LIMIT 1), (SELECT id FROM genres WHERE name='Novella' LIMIT 1)),
    ((SELECT id FROM books WHERE title='First They Killed My Father' LIMIT 1), (SELECT id FROM genres WHERE name='Memoir' LIMIT 1)),
    ((SELECT id FROM books WHERE title='First They Killed My Father' LIMIT 1), (SELECT id FROM genres WHERE name='Historical' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Frankenstein' LIMIT 1), (SELECT id FROM genres WHERE name='Horror' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Frankenstein' LIMIT 1), (SELECT id FROM genres WHERE name='Gothic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Romanovs' LIMIT 1), (SELECT id FROM genres WHERE name='History' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Romanovs' LIMIT 1), (SELECT id FROM genres WHERE name='Biography' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Steppenwolf' LIMIT 1), (SELECT id FROM genres WHERE name='Philosophical' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Steppenwolf' LIMIT 1), (SELECT id FROM genres WHERE name='Fiction' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Count of Monte Cristo' LIMIT 1), (SELECT id FROM genres WHERE name='Adventure' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Count of Monte Cristo' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Boy in the Striped Pyjamas' LIMIT 1), (SELECT id FROM genres WHERE name='Young Adult' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Boy in the Striped Pyjamas' LIMIT 1), (SELECT id FROM genres WHERE name='Historical' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Book Thief' LIMIT 1), (SELECT id FROM genres WHERE name='Historical' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Book Thief' LIMIT 1), (SELECT id FROM genres WHERE name='Drama' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Bell Jar' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Bell Jar' LIMIT 1), (SELECT id FROM genres WHERE name='Literary Fiction' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Breakfast at Tiffany''s' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Breakfast at Tiffany''s' LIMIT 1), (SELECT id FROM genres WHERE name='Literary Fiction' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Murder on the Orient Express' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Murder on the Orient Express' LIMIT 1), (SELECT id FROM genres WHERE name='Literary Fiction' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Catcher in the Rye' LIMIT 1), (SELECT id FROM genres WHERE name='Mystery' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Catcher in the Rye' LIMIT 1), (SELECT id FROM genres WHERE name='Crime' LIMIT 1)),
    ((SELECT id FROM books WHERE title='And Then There Were None' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='And Then There Were None' LIMIT 1), (SELECT id FROM genres WHERE name='Literary Fiction' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Dinosaur Feather' LIMIT 1), (SELECT id FROM genres WHERE name='Mystery' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Dinosaur Feather' LIMIT 1), (SELECT id FROM genres WHERE name='Crime' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Baltagul' LIMIT 1), (SELECT id FROM genres WHERE name='Mystery' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Baltagul' LIMIT 1), (SELECT id FROM genres WHERE name='Crime' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Moara cu noroc' LIMIT 1), (SELECT id FROM genres WHERE name='Literary Fiction' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Man''s Search for Meaning' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Man''s Search for Meaning' LIMIT 1), (SELECT id FROM genres WHERE name='Romanian Literature' LIMIT 1)),
    ((SELECT id FROM books WHERE title='25 Ways to Win People Over' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='25 Ways to Win People Over' LIMIT 1), (SELECT id FROM genres WHERE name='Romanian Literature' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Fresh Water for Flowers' LIMIT 1), (SELECT id FROM genres WHERE name='Philosophical' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Fresh Water for Flowers' LIMIT 1), (SELECT id FROM genres WHERE name='Psychology' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Letters to a Young Poet' LIMIT 1), (SELECT id FROM genres WHERE name='Self-help' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Letters to a Young Poet' LIMIT 1), (SELECT id FROM genres WHERE name='Business' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Behind Her Eyes' LIMIT 1), (SELECT id FROM genres WHERE name='Contemporary' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Behind Her Eyes' LIMIT 1), (SELECT id FROM genres WHERE name='Romance' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Postman Always Rings Twice' LIMIT 1), (SELECT id FROM genres WHERE name='Philosophical' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Postman Always Rings Twice' LIMIT 1), (SELECT id FROM genres WHERE name='Letters' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Notre-Dame de Paris' LIMIT 1), (SELECT id FROM genres WHERE name='Psychological' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Notre-Dame de Paris' LIMIT 1), (SELECT id FROM genres WHERE name='Thriller' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Nunta in cer' LIMIT 1), (SELECT id FROM genres WHERE name='Crime' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Nunta in cer' LIMIT 1), (SELECT id FROM genres WHERE name='Thriller' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Povestea lui Harap-Alb' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Povestea lui Harap-Alb' LIMIT 1), (SELECT id FROM genres WHERE name='Historical' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Maitreyi' LIMIT 1), (SELECT id FROM genres WHERE name='Philosophical' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Maitreyi' LIMIT 1), (SELECT id FROM genres WHERE name='Romance' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Hunger Games' LIMIT 1), (SELECT id FROM genres WHERE name='Fairy Tale' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Hunger Games' LIMIT 1), (SELECT id FROM genres WHERE name='Fantasy' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Catching Fire' LIMIT 1), (SELECT id FROM genres WHERE name='Philosophical' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Catching Fire' LIMIT 1), (SELECT id FROM genres WHERE name='Romance' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Most Cruel Women in History' LIMIT 1), (SELECT id FROM genres WHERE name='Dystopian' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Most Cruel Women in History' LIMIT 1), (SELECT id FROM genres WHERE name='Young Adult' LIMIT 1)),
    ((SELECT id FROM books WHERE title='House of Gucci' LIMIT 1), (SELECT id FROM genres WHERE name='Dystopian' LIMIT 1)),
    ((SELECT id FROM books WHERE title='House of Gucci' LIMIT 1), (SELECT id FROM genres WHERE name='Young Adult' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Razbunarea slutilor' LIMIT 1), (SELECT id FROM genres WHERE name='History' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Razbunarea slutilor' LIMIT 1), (SELECT id FROM genres WHERE name='Non-fiction' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Poezii' LIMIT 1), (SELECT id FROM genres WHERE name='Biography' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Poezii' LIMIT 1), (SELECT id FROM genres WHERE name='Business' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Alice''s Adventures in Wonderland' LIMIT 1), (SELECT id FROM genres WHERE name='Mystery' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Alice''s Adventures in Wonderland' LIMIT 1), (SELECT id FROM genres WHERE name='Crime' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Through the Looking-Glass' LIMIT 1), (SELECT id FROM genres WHERE name='Poetry' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Through the Looking-Glass' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Oscar and the Lady in Pink' LIMIT 1), (SELECT id FROM genres WHERE name='Fantasy' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Oscar and the Lady in Pink' LIMIT 1), (SELECT id FROM genres WHERE name='Adventure' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Promise of a Lie' LIMIT 1), (SELECT id FROM genres WHERE name='Fantasy' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Promise of a Lie' LIMIT 1), (SELECT id FROM genres WHERE name='Adventure' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Midnight Library' LIMIT 1), (SELECT id FROM genres WHERE name='Philosophical' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Midnight Library' LIMIT 1), (SELECT id FROM genres WHERE name='Drama' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Barbatii sunt niste porci' LIMIT 1), (SELECT id FROM genres WHERE name='Thriller' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Barbatii sunt niste porci' LIMIT 1), (SELECT id FROM genres WHERE name='Mystery' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Prophet' LIMIT 1), (SELECT id FROM genres WHERE name='Fantasy' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Prophet' LIMIT 1), (SELECT id FROM genres WHERE name='Drama' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Lord of the Flies' LIMIT 1), (SELECT id FROM genres WHERE name='Satire' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Lord of the Flies' LIMIT 1), (SELECT id FROM genres WHERE name='Philosophy' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Diary of a Young Girl' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Diary of a Young Girl' LIMIT 1), (SELECT id FROM genres WHERE name='Allegory' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Too Loud a Solitude' LIMIT 1), (SELECT id FROM genres WHERE name='Biography' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Too Loud a Solitude' LIMIT 1), (SELECT id FROM genres WHERE name='Memoir' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Setea muntelui de sare' LIMIT 1), (SELECT id FROM genres WHERE name='Literary Fiction' LIMIT 1)),
    ((SELECT id FROM books WHERE title='12 Creators Who Changed History' LIMIT 1), (SELECT id FROM genres WHERE name='Poetry' LIMIT 1)),
    ((SELECT id FROM books WHERE title='12 Creators Who Changed History' LIMIT 1), (SELECT id FROM genres WHERE name='Drama' LIMIT 1)),
    ((SELECT id FROM books WHERE title='How to Win Friends and Influence People' LIMIT 1), (SELECT id FROM genres WHERE name='History' LIMIT 1)),
    ((SELECT id FROM books WHERE title='How to Win Friends and Influence People' LIMIT 1), (SELECT id FROM genres WHERE name='Biography' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Sharp Objects' LIMIT 1), (SELECT id FROM genres WHERE name='Self-help' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Sharp Objects' LIMIT 1), (SELECT id FROM genres WHERE name='Business' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Anna Karenina' LIMIT 1), (SELECT id FROM genres WHERE name='Thriller' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Anna Karenina' LIMIT 1), (SELECT id FROM genres WHERE name='Mystery' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Screwtape Letters' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Screwtape Letters' LIMIT 1), (SELECT id FROM genres WHERE name='Romance' LIMIT 1)),
    ((SELECT id FROM books WHERE title='A Gentleman in Moscow' LIMIT 1), (SELECT id FROM genres WHERE name='Satire' LIMIT 1)),
    ((SELECT id FROM books WHERE title='A Gentleman in Moscow' LIMIT 1), (SELECT id FROM genres WHERE name='Fiction' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Animal Farm' LIMIT 1), (SELECT id FROM genres WHERE name='Philosophical' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Animal Farm' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Flowers of Evil' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Flowers of Evil' LIMIT 1), (SELECT id FROM genres WHERE name='Dystopian' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Jar City' LIMIT 1), (SELECT id FROM genres WHERE name='Poetry' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Jar City' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Mesterul Manole' LIMIT 1), (SELECT id FROM genres WHERE name='Crime' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Mesterul Manole' LIMIT 1), (SELECT id FROM genres WHERE name='Thriller' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Notes from Underground' LIMIT 1), (SELECT id FROM genres WHERE name='Drama' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Notes from Underground' LIMIT 1), (SELECT id FROM genres WHERE name='Mythology' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Uncle Tom’s Cabin' LIMIT 1), (SELECT id FROM genres WHERE name='Philosophical' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Uncle Tom’s Cabin' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Poezii' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Poezii' LIMIT 1), (SELECT id FROM genres WHERE name='American Literature' LIMIT 1)),
    ((SELECT id FROM books WHERE title='One Flew Over the Cuckoo’s Nest' LIMIT 1), (SELECT id FROM genres WHERE name='Poetry' LIMIT 1)),
    ((SELECT id FROM books WHERE title='One Flew Over the Cuckoo’s Nest' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Unwomanly Face of War' LIMIT 1), (SELECT id FROM genres WHERE name='Psychological' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Unwomanly Face of War' LIMIT 1), (SELECT id FROM genres WHERE name='Drama' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Great Stories of an Antiquary' LIMIT 1), (SELECT id FROM genres WHERE name='History' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Great Stories of an Antiquary' LIMIT 1), (SELECT id FROM genres WHERE name='Non-fiction' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Ultima noapte de dragoste, intaia noapte de razboi' LIMIT 1), (SELECT id FROM genres WHERE name='Horror' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Ultima noapte de dragoste, intaia noapte de razboi' LIMIT 1), (SELECT id FROM genres WHERE name='Gothic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='On the Shortness of Life' LIMIT 1), (SELECT id FROM genres WHERE name='Philosophical' LIMIT 1)),
    ((SELECT id FROM books WHERE title='On the Shortness of Life' LIMIT 1), (SELECT id FROM genres WHERE name='Essay' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Cianura pentru un suras' LIMIT 1), (SELECT id FROM genres WHERE name='Crime' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Cianura pentru un suras' LIMIT 1), (SELECT id FROM genres WHERE name='Thriller' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Crime and Punishment' LIMIT 1), (SELECT id FROM genres WHERE name='Philosophical' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Crime and Punishment' LIMIT 1), (SELECT id FROM genres WHERE name='Self-help' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Power of Now' LIMIT 1), (SELECT id FROM genres WHERE name='Detective' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Power of Now' LIMIT 1), (SELECT id FROM genres WHERE name='Mystery' LIMIT 1)),
    ((SELECT id FROM books WHERE title='A Study in Scarlet' LIMIT 1), (SELECT id FROM genres WHERE name='Contemporary' LIMIT 1)),
    ((SELECT id FROM books WHERE title='A Study in Scarlet' LIMIT 1), (SELECT id FROM genres WHERE name='Drama' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Where the Crawdads Sing' LIMIT 1), (SELECT id FROM genres WHERE name='Detective' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Where the Crawdads Sing' LIMIT 1), (SELECT id FROM genres WHERE name='Mystery' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Sign of Four' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Sign of Four' LIMIT 1), (SELECT id FROM genres WHERE name='Romanian Literature' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Morometii' LIMIT 1), (SELECT id FROM genres WHERE name='Poetry' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Morometii' LIMIT 1), (SELECT id FROM genres WHERE name='Romance' LIMIT 1)),
    ((SELECT id FROM books WHERE title='111 cele mai frumoase poezii de dragoste din literatura romana' LIMIT 1), (SELECT id FROM genres WHERE name='Memoir' LIMIT 1)),
    ((SELECT id FROM books WHERE title='111 cele mai frumoase poezii de dragoste din literatura romana' LIMIT 1), (SELECT id FROM genres WHERE name='Medical' LIMIT 1)),
    ((SELECT id FROM books WHERE title='When Breath Becomes Air' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='When Breath Becomes Air' LIMIT 1), (SELECT id FROM genres WHERE name='Gothic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Picture of Dorian Gray' LIMIT 1), (SELECT id FROM genres WHERE name='Satire' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Picture of Dorian Gray' LIMIT 1), (SELECT id FROM genres WHERE name='Philosophy' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Dictionary of Received Ideas' LIMIT 1), (SELECT id FROM genres WHERE name='Philosophical' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Dictionary of Received Ideas' LIMIT 1), (SELECT id FROM genres WHERE name='Poetry' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Little Book of Love' LIMIT 1), (SELECT id FROM genres WHERE name='Drama' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Little Book of Love' LIMIT 1), (SELECT id FROM genres WHERE name='Psychological' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Queen''s Gambit' LIMIT 1), (SELECT id FROM genres WHERE name='Dystopian' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Queen''s Gambit' LIMIT 1), (SELECT id FROM genres WHERE name='Fiction' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Enigma Otiliei' LIMIT 1), (SELECT id FROM genres WHERE name='Self-help' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Enigma Otiliei' LIMIT 1), (SELECT id FROM genres WHERE name='Relationships' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Handmaid’s Tale' LIMIT 1), (SELECT id FROM genres WHERE name='Psychological' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Handmaid’s Tale' LIMIT 1), (SELECT id FROM genres WHERE name='Philosophy' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The 5 Love Languages' LIMIT 1), (SELECT id FROM genres WHERE name='Thriller' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The 5 Love Languages' LIMIT 1), (SELECT id FROM genres WHERE name='Mystery' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Staring at the Sun' LIMIT 1), (SELECT id FROM genres WHERE name='Fantasy' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Staring at the Sun' LIMIT 1), (SELECT id FROM genres WHERE name='Young Adult' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Da Vinci Code' LIMIT 1), (SELECT id FROM genres WHERE name='Fantasy' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Da Vinci Code' LIMIT 1), (SELECT id FROM genres WHERE name='Young Adult' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Harry Potter and the Philosopher’s Stone' LIMIT 1), (SELECT id FROM genres WHERE name='Fantasy' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Harry Potter and the Philosopher’s Stone' LIMIT 1), (SELECT id FROM genres WHERE name='Young Adult' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Harry Potter and the Chamber of Secrets' LIMIT 1), (SELECT id FROM genres WHERE name='Fantasy' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Harry Potter and the Chamber of Secrets' LIMIT 1), (SELECT id FROM genres WHERE name='Young Adult' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Harry Potter and the Prisoner of Azkaban' LIMIT 1), (SELECT id FROM genres WHERE name='Fantasy' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Harry Potter and the Prisoner of Azkaban' LIMIT 1), (SELECT id FROM genres WHERE name='Young Adult' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Harry Potter and The Goblet of Fire' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Harry Potter and The Goblet of Fire' LIMIT 1), (SELECT id FROM genres WHERE name='Adventure' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Harry Potter and the Order of the Phoenix' LIMIT 1), (SELECT id FROM genres WHERE name='Contemporary' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Harry Potter and the Order of the Phoenix' LIMIT 1), (SELECT id FROM genres WHERE name='Fiction' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Old Man and the Sea' LIMIT 1), (SELECT id FROM genres WHERE name='Fantasy' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Old Man and the Sea' LIMIT 1), (SELECT id FROM genres WHERE name='Young Adult' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Housekeeper and the Professor' LIMIT 1), (SELECT id FROM genres WHERE name='Fantasy' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Housekeeper and the Professor' LIMIT 1), (SELECT id FROM genres WHERE name='Young Adult' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Harry Potter and the Half-Blood Prince' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Harry Potter and the Half-Blood Prince' LIMIT 1), (SELECT id FROM genres WHERE name='Christmas' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Harry Potter and the Deathly Hallows' LIMIT 1), (SELECT id FROM genres WHERE name='Drama' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Harry Potter and the Deathly Hallows' LIMIT 1), (SELECT id FROM genres WHERE name='Legal' LIMIT 1)),
    ((SELECT id FROM books WHERE title='A Christmas Carol' LIMIT 1), (SELECT id FROM genres WHERE name='Philosophical' LIMIT 1)),
    ((SELECT id FROM books WHERE title='A Christmas Carol' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Apararea are cuvantul' LIMIT 1), (SELECT id FROM genres WHERE name='Philosophical' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Apararea are cuvantul' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Drive Your Plow Over the Bones of the Dead' LIMIT 1), (SELECT id FROM genres WHERE name='Literary Fiction' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Drive Your Plow Over the Bones of the Dead' LIMIT 1), (SELECT id FROM genres WHERE name='Mystery' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Kreutzer Sonata' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Kreutzer Sonata' LIMIT 1), (SELECT id FROM genres WHERE name='Coming-of-age' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Death of Ivan Ilych' LIMIT 1), (SELECT id FROM genres WHERE name='Mystery' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Death of Ivan Ilych' LIMIT 1), (SELECT id FROM genres WHERE name='Crime' LIMIT 1)),
    ((SELECT id FROM books WHERE title='To Kill a Mockingbird' LIMIT 1), (SELECT id FROM genres WHERE name='Philosophical' LIMIT 1)),
    ((SELECT id FROM books WHERE title='To Kill a Mockingbird' LIMIT 1), (SELECT id FROM genres WHERE name='Fiction' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Murder of Roger Ackroyd' LIMIT 1), (SELECT id FROM genres WHERE name='Psychological' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Murder of Roger Ackroyd' LIMIT 1), (SELECT id FROM genres WHERE name='Thriller' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Metamorphosis' LIMIT 1), (SELECT id FROM genres WHERE name='Philosophical' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Metamorphosis' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Perfume: The Story of a Murderer' LIMIT 1), (SELECT id FROM genres WHERE name='Contemporary' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Perfume: The Story of a Murderer' LIMIT 1), (SELECT id FROM genres WHERE name='Romance' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Art of Living' LIMIT 1), (SELECT id FROM genres WHERE name='Philosophical' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Art of Living' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Norwegian Wood' LIMIT 1), (SELECT id FROM genres WHERE name='Horror' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Norwegian Wood' LIMIT 1), (SELECT id FROM genres WHERE name='Thriller' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Sorrows of Young Werther' LIMIT 1), (SELECT id FROM genres WHERE name='Crime' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Sorrows of Young Werther' LIMIT 1), (SELECT id FROM genres WHERE name='Mystery' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Carrie' LIMIT 1), (SELECT id FROM genres WHERE name='Contemporary' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Carrie' LIMIT 1), (SELECT id FROM genres WHERE name='Science' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Crima prin mica publicitate' LIMIT 1), (SELECT id FROM genres WHERE name='Mystery' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Crima prin mica publicitate' LIMIT 1), (SELECT id FROM genres WHERE name='Crime' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Lessons in Chemistry' LIMIT 1), (SELECT id FROM genres WHERE name='Self-help' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Lessons in Chemistry' LIMIT 1), (SELECT id FROM genres WHERE name='Psychology' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Evil Under the Sun' LIMIT 1), (SELECT id FROM genres WHERE name='Thriller' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Evil Under the Sun' LIMIT 1), (SELECT id FROM genres WHERE name='Mystery' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Reasons to Stay Alive' LIMIT 1), (SELECT id FROM genres WHERE name='Poetry' LIMIT 1)),
    ((SELECT id FROM books WHERE title='Reasons to Stay Alive' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Perfect Son' LIMIT 1), (SELECT id FROM genres WHERE name='Poetry' LIMIT 1)),
    ((SELECT id FROM books WHERE title='The Perfect Son' LIMIT 1), (SELECT id FROM genres WHERE name='Classic' LIMIT 1))
ON CONFLICT DO NOTHING;
